//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascentis.Ecommerce.BuddiesPortal.ConcessionaireWCFClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConcessionaireWCFClient.IConcessionaireService")]
    public interface IConcessionaireService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConcessionaireService/GetConcessionaireListByGroupIDWithJson", ReplyAction="http://tempuri.org/IConcessionaireService/GetConcessionaireListByGroupIDWithJsonR" +
            "esponse")]
        string GetConcessionaireListByGroupIDWithJson(long groupID, int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConcessionaireServiceChannel : Ascentis.Ecommerce.BuddiesPortal.ConcessionaireWCFClient.IConcessionaireService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConcessionaireServiceClient : System.ServiceModel.ClientBase<Ascentis.Ecommerce.BuddiesPortal.ConcessionaireWCFClient.IConcessionaireService>, Ascentis.Ecommerce.BuddiesPortal.ConcessionaireWCFClient.IConcessionaireService {
        
        public ConcessionaireServiceClient() {
        }
        
        public ConcessionaireServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConcessionaireServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcessionaireServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcessionaireServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetConcessionaireListByGroupIDWithJson(long groupID, int count) {
            return base.Channel.GetConcessionaireListByGroupIDWithJson(groupID, count);
        }
    }
}
