//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascentis.Ecommerce.BuddiesPortal.TransactionServiceWCFClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransactionServiceWCFClient.ITransactionService")]
    public interface ITransactionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/GetAllTransactions", ReplyAction="http://tempuri.org/ITransactionService/GetAllTransactionsResponse")]
        Ascentis.Ecommerce.DataEntity.WebUIEntity.TransactionEntity[] GetAllTransactions(long memberAutoId, string memberName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/ReOrder", ReplyAction="http://tempuri.org/ITransactionService/ReOrderResponse")]
        string ReOrder(Ascentis.Ecommerce.DataEntity.WebUIEntity.TransactionEntity transactionEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionService/UpdateOrderStatusFromOfs", ReplyAction="http://tempuri.org/ITransactionService/UpdateOrderStatusFromOfsResponse")]
        Ascentis.Ecommerce.DataEntity.WebUIEntity.TransactionEntity[] UpdateOrderStatusFromOfs(Ascentis.Ecommerce.DataEntity.WebUIEntity.TransactionEntity[] transBatch);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionServiceChannel : Ascentis.Ecommerce.BuddiesPortal.TransactionServiceWCFClient.ITransactionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionServiceClient : System.ServiceModel.ClientBase<Ascentis.Ecommerce.BuddiesPortal.TransactionServiceWCFClient.ITransactionService>, Ascentis.Ecommerce.BuddiesPortal.TransactionServiceWCFClient.ITransactionService {
        
        public TransactionServiceClient() {
        }
        
        public TransactionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ascentis.Ecommerce.DataEntity.WebUIEntity.TransactionEntity[] GetAllTransactions(long memberAutoId, string memberName) {
            return base.Channel.GetAllTransactions(memberAutoId, memberName);
        }
        
        public string ReOrder(Ascentis.Ecommerce.DataEntity.WebUIEntity.TransactionEntity transactionEntity) {
            return base.Channel.ReOrder(transactionEntity);
        }
        
        public Ascentis.Ecommerce.DataEntity.WebUIEntity.TransactionEntity[] UpdateOrderStatusFromOfs(Ascentis.Ecommerce.DataEntity.WebUIEntity.TransactionEntity[] transBatch) {
            return base.Channel.UpdateOrderStatusFromOfs(transBatch);
        }
    }
}
