//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolut.
        /// </summary>
        internal static string Absolut {
            get {
                return ResourceManager.GetString("Absolut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acqua Di Parma.
        /// </summary>
        internal static string AcquaDiParma {
            get {
                return ResourceManager.GetString("AcquaDiParma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO CART.
        /// </summary>
        internal static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO WISHLIST.
        /// </summary>
        internal static string AddToWishlist {
            get {
                return ResourceManager.GetString("AddToWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advocaat.
        /// </summary>
        internal static string Advocaat {
            get {
                return ResourceManager.GetString("Advocaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aftershock.
        /// </summary>
        internal static string Aftershock {
            get {
                return ResourceManager.GetString("Aftershock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        internal static string Alberta {
            get {
                return ResourceManager.GetString("Alberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alize.
        /// </summary>
        internal static string Alize {
            get {
                return ResourceManager.GetString("Alize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaretto Di Saronno.
        /// </summary>
        internal static string AmarettoDiSaronno {
            get {
                return ResourceManager.GetString("AmarettoDiSaronno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amer Picon.
        /// </summary>
        internal static string AmerPicon {
            get {
                return ResourceManager.GetString("AmerPicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperol.
        /// </summary>
        internal static string Aperol {
            get {
                return ResourceManager.GetString("Aperol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apfelkorn.
        /// </summary>
        internal static string Apfelkorn {
            get {
                return ResourceManager.GetString("Apfelkorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applejack.
        /// </summary>
        internal static string Applejack {
            get {
                return ResourceManager.GetString("Applejack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquolina.
        /// </summary>
        internal static string Aquolina {
            get {
                return ResourceManager.GetString("Aquolina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archers.
        /// </summary>
        internal static string Archers {
            get {
                return ResourceManager.GetString("Archers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artic.
        /// </summary>
        internal static string Artic {
            get {
                return ResourceManager.GetString("Artic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aslanov.
        /// </summary>
        internal static string Aslanov {
            get {
                return ResourceManager.GetString("Aslanov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99 Bananas.
        /// </summary>
        internal static string Bananas99 {
            get {
                return ResourceManager.GetString("Bananas99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty.
        /// </summary>
        internal static string Beauty {
            get {
                return ResourceManager.GetString("Beauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Sellers.
        /// </summary>
        internal static string BestSellers {
            get {
                return ResourceManager.GetString("BestSellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        internal static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iShopChangi.
        /// </summary>
        internal static string Changi {
            get {
                return ResourceManager.GetString("Changi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolates &amp; Snacks.
        /// </summary>
        internal static string ChocolatesSnacks {
            get {
                return ResourceManager.GetString("ChocolatesSnacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filters.
        /// </summary>
        internal static string ClearAllFilters {
            get {
                return ResourceManager.GetString("ClearAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Shopping.
        /// </summary>
        internal static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Travel.
        /// </summary>
        internal static string DateOfTravel {
            get {
                return ResourceManager.GetString("DateOfTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFSGalleria.
        /// </summary>
        internal static string DFSGalleria {
            get {
                return ResourceManager.GetString("DFSGalleria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond-Patterned Collapsible Umbrella.
        /// </summary>
        internal static string DiamondPatternedCollapsibleUmbrella {
            get {
                return ResourceManager.GetString("DiamondPatternedCollapsibleUmbrella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNTOWN.
        /// </summary>
        internal static string Downtown {
            get {
                return ResourceManager.GetString("Downtown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITOR&apos;S.
        /// </summary>
        internal static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor&apos;s Pick.
        /// </summary>
        internal static string EditorPick {
            get {
                return ResourceManager.GetString("EditorPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your flight details before proceeding:.
        /// </summary>
        internal static string EenterFlightDetails {
            get {
                return ResourceManager.GetString("EenterFlightDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Destination.
        /// </summary>
        internal static string EnterDestination {
            get {
                return ResourceManager.GetString("EnterDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Flight No..
        /// </summary>
        internal static string EnterFlightNo {
            get {
                return ResourceManager.GetString("EnterFlightNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estee Lauder DayWear Plus Multi Protection Anti-Oxidant Creme SPF 15.
        /// </summary>
        internal static string EsteeLauderDayWear {
            get {
                return ResourceManager.GetString("EsteeLauderDayWear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive.
        /// </summary>
        internal static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair Isle Socks.
        /// </summary>
        internal static string FairIsleSocks {
            get {
                return ResourceManager.GetString("FairIsleSocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        internal static string Filterby {
            get {
                return ResourceManager.GetString("Filterby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Info.
        /// </summary>
        internal static string FlightInfo {
            get {
                return ResourceManager.GetString("FlightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight No. (Optional).
        /// </summary>
        internal static string FlightNOptional {
            get {
                return ResourceManager.GetString("FlightNOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        internal static string Gifts {
            get {
                return ResourceManager.GetString("Gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gin.
        /// </summary>
        internal static string Gin {
            get {
                return ResourceManager.GetString("Gin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST.
        /// </summary>
        internal static string GST {
            get {
                return ResourceManager.GetString("GST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock.
        /// </summary>
        internal static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT &amp; Electronics.
        /// </summary>
        internal static string ITElectronics {
            get {
                return ResourceManager.GetString("ITElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in Cart.
        /// </summary>
        internal static string ItemsInCart {
            get {
                return ResourceManager.GetString("ItemsInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in Wishlist.
        /// </summary>
        internal static string ItemsInWishlist {
            get {
                return ResourceManager.GetString("ItemsInWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        internal static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        internal static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIKE.
        /// </summary>
        internal static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liqueurs.
        /// </summary>
        internal static string Liqueurs {
            get {
                return ResourceManager.GetString("Liqueurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More.
        /// </summary>
        internal static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More images....
        /// </summary>
        internal static string MoreImages {
            get {
                return ResourceManager.GetString("MoreImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICK.
        /// </summary>
        internal static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        internal static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Viewed Items.
        /// </summary>
        internal static string RecentlyViewedItems {
            get {
                return ResourceManager.GetString("RecentlyViewedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Items.
        /// </summary>
        internal static string RecommendedItems {
            get {
                return ResourceManager.GetString("RecommendedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Wine.
        /// </summary>
        internal static string RedWine {
            get {
                return ResourceManager.GetString("RedWine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailers.
        /// </summary>
        internal static string Retailers {
            get {
                return ResourceManager.GetString("Retailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVINGS.
        /// </summary>
        internal static string Savings {
            get {
                return ResourceManager.GetString("Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300 Series Chronograph Wristwatch.
        /// </summary>
        internal static string SeriesChronographWristwatch300 {
            get {
                return ResourceManager.GetString("SeriesChronographWristwatch300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLD OUT.
        /// </summary>
        internal static string SoldOut {
            get {
                return ResourceManager.GetString("SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirits.
        /// </summary>
        internal static string Spirits {
            get {
                return ResourceManager.GetString("Spirits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Categories.
        /// </summary>
        internal static string SubCategories {
            get {
                return ResourceManager.GetString("SubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suede and Leather Boat Shoes.
        /// </summary>
        internal static string SuedeLeatherBoatShoes {
            get {
                return ResourceManager.GetString("SuedeLeatherBoatShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timepiece.
        /// </summary>
        internal static string Timepiece {
            get {
                return ResourceManager.GetString("Timepiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ITEM.
        /// </summary>
        internal static string ViemItem {
            get {
                return ResourceManager.GetString("ViemItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Strap Three Pack.
        /// </summary>
        internal static string WatchStrapThreePack {
            get {
                return ResourceManager.GetString("WatchStrapThreePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Wine.
        /// </summary>
        internal static string WhiteWine {
            get {
                return ResourceManager.GetString("WhiteWine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine.
        /// </summary>
        internal static string Wine {
            get {
                return ResourceManager.GetString("Wine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine &amp; Spirits.
        /// </summary>
        internal static string WineSpirits {
            get {
                return ResourceManager.GetString("WineSpirits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        internal static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
    }
}
