//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascentis.Ecommerce.BuddiesPortal.LanguageMasterWCFClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LanguageMasterWCFClient.ILanguageMasterService")]
    public interface ILanguageMasterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILanguageMasterService/GetLanguageMasterWithJson", ReplyAction="http://tempuri.org/ILanguageMasterService/GetLanguageMasterWithJsonResponse")]
        string GetLanguageMasterWithJson();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILanguageMasterServiceChannel : Ascentis.Ecommerce.BuddiesPortal.LanguageMasterWCFClient.ILanguageMasterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LanguageMasterServiceClient : System.ServiceModel.ClientBase<Ascentis.Ecommerce.BuddiesPortal.LanguageMasterWCFClient.ILanguageMasterService>, Ascentis.Ecommerce.BuddiesPortal.LanguageMasterWCFClient.ILanguageMasterService {
        
        public LanguageMasterServiceClient() {
        }
        
        public LanguageMasterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LanguageMasterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LanguageMasterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LanguageMasterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLanguageMasterWithJson() {
            return base.Channel.GetLanguageMasterWithJson();
        }
    }
}
